/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from lexboxClientContracts.IEntry */
export type IEntry = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from lexboxClientContracts.IMultiString */
    lexemeForm: IMultiString;
    /** Transpiled from lexboxClientContracts.IMultiString */
    citationForm: IMultiString;
    /** Transpiled from lexboxClientContracts.IMultiString */
    literalMeaning: IMultiString;
    /** Transpiled from System.Collections.Generic.IList<lexboxClientContracts.ISense> */
    senses: ISense[];
    /** Transpiled from lexboxClientContracts.IMultiString */
    note: IMultiString;
}

/** Transpiled from lexboxClientContracts.Entry */
export type Entry = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from lexboxClientContracts.IMultiString */
    lexemeForm: IMultiString;
    /** Transpiled from lexboxClientContracts.IMultiString */
    citationForm: IMultiString;
    /** Transpiled from lexboxClientContracts.IMultiString */
    literalMeaning: IMultiString;
    /** Transpiled from System.Collections.Generic.IList<lexboxClientContracts.ISense> */
    senses: ISense[];
    /** Transpiled from lexboxClientContracts.IMultiString */
    note: IMultiString;
}

/** Transpiled from lexboxClientContracts.IExampleSentence */
export type IExampleSentence = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from lexboxClientContracts.IMultiString */
    sentence: IMultiString;
    /** Transpiled from lexboxClientContracts.IMultiString */
    translation: IMultiString;
    /** Transpiled from string */
    reference: string;
}

/** Transpiled from lexboxClientContracts.ExampleSentence */
export type ExampleSentence = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from lexboxClientContracts.IMultiString */
    sentence: IMultiString;
    /** Transpiled from lexboxClientContracts.IMultiString */
    translation: IMultiString;
    /** Transpiled from string */
    reference: string;
}

/** Transpiled from lexboxClientContracts.QueryOptions */
export type QueryOptions = {
    /** Transpiled from string */
    order: string;
    /** Transpiled from int */
    count: number;
    /** Transpiled from int */
    offset: number;
}

/** Transpiled from lexboxClientContracts.IMultiString */
export type IMultiString = {
    /** Transpiled from System.Collections.Generic.IDictionary<lexboxClientContracts.WritingSystemId, string> */
    values: { [key: WritingSystemId]: string };
}

/** Transpiled from lexboxClientContracts.ISense */
export type ISense = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from lexboxClientContracts.IMultiString */
    definition: IMultiString;
    /** Transpiled from lexboxClientContracts.IMultiString */
    gloss: IMultiString;
    /** Transpiled from string */
    partOfSpeech: string;
    /** Transpiled from System.Collections.Generic.IList<string> */
    semanticDomain: string[];
    /** Transpiled from System.Collections.Generic.IList<lexboxClientContracts.IExampleSentence> */
    exampleSentences: IExampleSentence[];
}

/** Transpiled from lexboxClientContracts.Sense */
export type Sense = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from lexboxClientContracts.IMultiString */
    definition: IMultiString;
    /** Transpiled from lexboxClientContracts.IMultiString */
    gloss: IMultiString;
    /** Transpiled from string */
    partOfSpeech: string;
    /** Transpiled from System.Collections.Generic.IList<string> */
    semanticDomain: string[];
    /** Transpiled from System.Collections.Generic.IList<lexboxClientContracts.IExampleSentence> */
    exampleSentences: IExampleSentence[];
}

/** Transpiled from lexboxClientContracts.WritingSystem */
export type WritingSystem = {
    /** Transpiled from lexboxClientContracts.WritingSystemId */
    id: WritingSystemId;
    /** Transpiled from string */
    name: string;
    /** Transpiled from string */
    abbreviation: string;
    /** Transpiled from string */
    font: string;
}

/** Transpiled from lexboxClientContracts.WritingSystems */
export type WritingSystems = {
    /** Transpiled from lexboxClientContracts.WritingSystem[] */
    analysis: WritingSystem[];
    /** Transpiled from lexboxClientContracts.WritingSystem[] */
    vernacular: WritingSystem[];
}

/** Transpiled from lexboxClientContracts.WritingSystemId */
export type WritingSystemId = string;

