/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { IStreamResult, Subject } from '@microsoft/signalr';
import { WritingSystems, QueryOptions, IEntry, Entry, Sense, ISense, ExampleSentence, IExampleSentence } from '../lexboxClientContracts';

export type JsonOperation = {
    /** Transpiled from string */
    op: string;
    /** Transpiled from string */
    path: string;
    /** Transpiled from object? */
    value?: any;
    /** Transpiled from string? */
    from?: string;
}
export type ILexboxApiHub = {
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<lexboxClientContracts.WritingSystems>
    */
    GetWritingSystems(): Promise<WritingSystems>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<string[]>
    */
    GetExemplars(): Promise<string[]>;
    /**
    * @param exemplar Transpiled from string
    * @param options Transpiled from lexboxClientContracts.QueryOptions?
    * @returns Transpiled from System.Threading.Tasks.Task<lexboxClientContracts.IEntry[]>
    */
    GetEntriesForExemplar(exemplar: string, options: QueryOptions): Promise<IEntry[]>;
    /**
    * @param options Transpiled from lexboxClientContracts.QueryOptions?
    * @returns Transpiled from System.Threading.Tasks.Task<lexboxClientContracts.IEntry[]>
    */
    GetEntries(options: QueryOptions): Promise<IEntry[]>;
    /**
    * @param query Transpiled from string
    * @param options Transpiled from lexboxClientContracts.QueryOptions?
    * @returns Transpiled from System.Threading.Tasks.Task<lexboxClientContracts.IEntry[]>
    */
    SearchEntries(query: string, options: QueryOptions): Promise<IEntry[]>;
    /**
    * @param id Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<lexboxClientContracts.IEntry>
    */
    GetEntry(id: string): Promise<IEntry>;
    /**
    * @param entry Transpiled from lexboxClientContracts.Entry
    * @returns Transpiled from System.Threading.Tasks.Task<lexboxClientContracts.IEntry>
    */
    CreateEntry(entry: Entry): Promise<IEntry>;
    /**
    * @param id Transpiled from System.Guid
    * @param update Transpiled from Lexbox.ClientServer.Hubs.JsonOperation[]
    * @returns Transpiled from System.Threading.Tasks.Task<lexboxClientContracts.IEntry>
    */
    UpdateEntry(id: string, update: JsonOperation[]): Promise<IEntry>;
    /**
    * @param id Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    DeleteEntry(id: string): Promise<void>;
    /**
    * @param entryId Transpiled from System.Guid
    * @param sense Transpiled from lexboxClientContracts.Sense
    * @returns Transpiled from System.Threading.Tasks.Task<lexboxClientContracts.ISense>
    */
    CreateSense(entryId: string, sense: Sense): Promise<ISense>;
    /**
    * @param entryId Transpiled from System.Guid
    * @param senseId Transpiled from System.Guid
    * @param update Transpiled from Lexbox.ClientServer.Hubs.JsonOperation[]
    * @returns Transpiled from System.Threading.Tasks.Task<lexboxClientContracts.ISense>
    */
    UpdateSense(entryId: string, senseId: string, update: JsonOperation[]): Promise<ISense>;
    /**
    * @param entryId Transpiled from System.Guid
    * @param senseId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    DeleteSense(entryId: string, senseId: string): Promise<void>;
    /**
    * @param entryId Transpiled from System.Guid
    * @param senseId Transpiled from System.Guid
    * @param exampleSentence Transpiled from lexboxClientContracts.ExampleSentence
    * @returns Transpiled from System.Threading.Tasks.Task<lexboxClientContracts.IExampleSentence>
    */
    CreateExampleSentence(entryId: string, senseId: string, exampleSentence: ExampleSentence): Promise<IExampleSentence>;
    /**
    * @param entryId Transpiled from System.Guid
    * @param senseId Transpiled from System.Guid
    * @param exampleSentenceId Transpiled from System.Guid
    * @param update Transpiled from Lexbox.ClientServer.Hubs.JsonOperation[]
    * @returns Transpiled from System.Threading.Tasks.Task<lexboxClientContracts.IExampleSentence>
    */
    UpdateExampleSentence(entryId: string, senseId: string, exampleSentenceId: string, update: JsonOperation[]): Promise<IExampleSentence>;
    /**
    * @param entryId Transpiled from System.Guid
    * @param senseId Transpiled from System.Guid
    * @param exampleSentenceId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    DeleteExampleSentence(entryId: string, senseId: string, exampleSentenceId: string): Promise<void>;
}

export type ILexboxClient = {
    /**
    * @param entry Transpiled from lexboxClientContracts.IEntry
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    OnEntryUpdated(entry: IEntry): Promise<void>;
}

