# https://taskfile.dev

version: '3'

tasks:
  run-android:
    cmd: dotnet build -f net8.0-android -t:"Build;Run" /p:CLIBuild=true

  run-windows-full:
    cmds:
      - dotnet build -f net8.0-windows10.0.19041.0 -t:"Build;Run" /p:CLIBuild=true

  run-windows:
    cmds:
      - dotnet build -f net8.0-windows10.0.19041.0 -t:"Run" /p:CLIBuild=true
