# https://taskfile.dev

version: '3'

tasks:
  run-android:
    cmds:
      - dotnet build -f net8.0-android
      - dotnet build -f net8.0-android -t:Run
  run-windows:
    cmds:
      - dotnet build -f net8.0-windows10.0.19041.0
      - dotnet build -f net8.0-windows10.0.19041.0 -t:Run
